#!/usr/bin/env python3
"""
Generate golden capture files for 3 new profiles under captures/<profile>/.
Produces: tls/client_hello.bin + .meta.json, http2/settings.bin + .meta.json.
SETTINGS frames are reconstructed from oracle data (they are non-randomized).
"""
import os, json, struct, shutil
from datetime import datetime, timezone

CAPTURES = "/Users/matte/projects/browsercore/testing/captures"
RAW = os.path.join(CAPTURES, "_probe", "raw_bytes")
ORACLE = os.path.join(CAPTURES, "_probe", "output")

CREATED_AT = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

# SETTINGS ID mapping (IANA HTTP/2 SETTINGS identifiers)
SETTING_IDS = {
    "HEADER_TABLE_SIZE": 0x0001,
    "ENABLE_PUSH": 0x0002,
    "MAX_CONCURRENT_STREAMS": 0x0003,
    "INITIAL_WINDOW_SIZE": 0x0004,
    "MAX_FRAME_SIZE": 0x0005,
    "MAX_HEADER_LIST_SIZE": 0x0006,
    "ENABLE_CONNECT_PROTOCOL": 0x0008,
    "NO_RFC7540_PRIORITIES": 0x0009,
}

def build_settings_frame(settings_list):
    """Build raw HTTP/2 SETTINGS frame bytes from ['KEY = VALUE', ...]."""
    payload = b""
    for s in settings_list:
        k, v = s.split(" = ", 1)
        sid = SETTING_IDS[k]
        payload += struct.pack(">H", sid) + struct.pack(">I", int(v))
    length = len(payload)
    # Frame header: 3-byte length, 1-byte type (0x04=SETTINGS), 1-byte flags, 4-byte stream id (0)
    header = struct.pack(">I", length)[1:] + bytes([0x04, 0x00]) + struct.pack(">I", 0)
    return header + payload

def write_meta(path, profile, protocol, record, description, randomized_fields):
    meta = {
        "source": "curl-impersonate",
        "profile": profile,
        "protocol": protocol,
        "record": record,
        "description": description,
        "randomizedFields": randomized_fields,
        "createdAt": CREATED_AT,
    }
    with open(path, "w") as f:
        json.dump(meta, f, indent=4)
        f.write("\n")

# Profile definitions: (oracle_profile, golden_name, client_hello_bin, randomized_fields_for_ch, settings_list)
PROFILES = []

# Build from captured data
def build_profile(oracle_name, golden_name, randomized_fields):
    cap_bin = os.path.join(RAW, f"{golden_name}_client_hello.bin")
    if not os.path.exists(cap_bin):
        print(f"  SKIP {golden_name}: no capture bytes")
        return
    with open(cap_bin, "rb") as d:
        ch_bytes = d.read()
    # load oracle for settings
    oracle_path = os.path.join(ORACLE, f"{oracle_name}.json")
    if not os.path.exists(oracle_path):
        oracle_path = os.path.join(ORACLE, f"{oracle_name}_fresh.json")
    with open(oracle_path) as f:
        od = json.load(f)
    settings_list = None
    for fr in od["http2"]["sent_frames"]:
        if fr["frame_type"] == "SETTINGS":
            settings_list = fr["settings"]
            break
    if settings_list is None:
        print(f"  SKIP {golden_name}: no SETTINGS in oracle")
        return

    base = os.path.join(CAPTURES, golden_name)
    tls_dir = os.path.join(base, "tls")
    h2_dir = os.path.join(base, "http2")
    os.makedirs(tls_dir, exist_ok=True)
    os.makedirs(h2_dir, exist_ok=True)

    # TLS client_hello
    ch_path = os.path.join(tls_dir, "client_hello.bin")
    with open(ch_path, "wb") as f:
        f.write(ch_bytes)
    write_meta(
        ch_path.replace(".bin", ".meta.json"),
        golden_name, "tls", "client_hello",
        f"TLS 1.3 ClientHello generated by curl-impersonate against {od['tls'].get('extensions',[{}])[2].get('server_name','example.com') if False else 'tls.peet.ws'} impersonating {oracle_name}. Captured via transparent SOCKS5 relay with correct SNI. Fields below are intentionally randomized per RFC 8446/8701 and must be masked during golden comparison (Cat 14).",
        randomized_fields,
    )

    # HTTP/2 settings
    settings_bytes = build_settings_frame(settings_list)
    settings_path = os.path.join(h2_dir, "settings.bin")
    with open(settings_path, "wb") as f:
        f.write(settings_bytes)
    write_meta(
        settings_path.replace(".bin", ".meta.json"),
        golden_name, "http2", "settings",
        f"First HTTP/2 SETTINGS frame sent by curl-impersonate {oracle_name}. HTTP/2 SETTINGS are not randomized, so the ignore-list is empty.",
        [],
    )

    # Also dump the full oracle capture as a reference JSON sidecar
    ref_path = os.path.join(base, "oracle_capture.reference.json")
    with open(ref_path, "w") as f:
        json.dump(od, f, indent=2)

    print(f"  CREATED {golden_name}: client_hello.bin={len(ch_bytes)}B, settings.bin={len(settings_bytes)}B")
    print(f"    settings frame: {settings_list}")
    return base

# chrome-131: non-deterministic ordering — mask ALL extension-related randomized ranges.
# Since the entire extension block order varies, we mask extensions (after session_id+random+ciphers+comp)
# and treat client_random + ephemeral as randomized. We compute offsets from actual bytes.
def chrome131_randomized(ch_bytes):
    """Compute randomized field ranges for chrome131 (everything that varies)."""
    pos = 9  # after record(5)+hs_type(1)+hs_len(3)
    ver = struct.unpack(">H", ch_bytes[pos:pos+2])[0]; pos += 2
    # random at offset 12 (absolute), length 32
    pos += 32
    sid = ch_bytes[pos]; pos += 1 + sid
    csl = struct.unpack(">H", ch_bytes[pos:pos+2])[0]; pos += 2
    ciphers_start = pos
    pos += csl
    comp = ch_bytes[pos]; pos += 1 + comp
    # extensions start here (absolute offset = pos). All of it varies in order + GREASE values.
    ext_start = pos
    return [
        {"byteOffset": 12, "length": 32, "reason": "random"},
        {"byteOffset": ext_start, "length": len(ch_bytes) - ext_start, "reason": "grease"},
    ]

def generic_randomized(ch_bytes):
    """random + grease for deterministic profiles (firefox, safari)."""
    pos = 9
    pos += 2  # ver
    # random at offset 12
    pos += 32
    sid = ch_bytes[pos]; pos += 1 + sid
    csl = struct.unpack(">H", ch_bytes[pos:pos+2])[0]; pos += 2
    pos += csl
    comp = ch_bytes[pos]; pos += 1 + comp
    ext_start = pos
    return [
        {"byteOffset": 12, "length": 32, "reason": "random"},
        {"byteOffset": ext_start, "length": len(ch_bytes) - ext_start, "reason": "grease"},
    ]

print("=== Generating golden captures ===\n")

for oracle_name, golden_name, rf_func in [
    ("chrome131", "chrome-131", chrome131_randomized),
    ("firefox133", "firefox-133", generic_randomized),
    ("safari170", "safari-17", generic_randomized),
]:
    print(f"--- {golden_name} ---")
    cap_bin = os.path.join(RAW, f"{golden_name}_client_hello.bin")
    with open(cap_bin, "rb") as f:
        ch = f.read()
    rf = rf_func(ch)
    print(f"  randomized fields: {rf}")
    build_profile(oracle_name, golden_name, rf)

print("\nDone.")
